<a href="https://colab.research.google.com/github/beatricenfodwaa-max/datasci_1_loading/blob/main/assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**the **

** The following code cell imports pandas and json**
  we need pandas because we cannot load our dataset without it

In [ ]:
import pandas as pd

import Json

In [ ]:
import pandas as pd

df1 ='/content/data /data1.csv'
read_csv1 = pd.read_csv(df1)
read_csv1.head(11)

,CMS Certification Number (CCN),Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,NATION,I_006_01_NATL_SIR,1.005,-,07/01/2024,06/30/2025,-
1,NATION,I_011_05_NATL_OBS_RATE,64.84,-,10/01/2024,09/30/2025,-
2,NATION,I_012_06_NATL_OBS_RATE,62.03,-,10/01/2024,09/30/2025,-
3,NATION,I_013_01_NATL_OBS_RATE,0.14,-,10/01/2024,09/30/2025,-
4,NATION,I_015_01_NATL_SIR,0.331,-,07/01/2024,06/30/2025,-
5,NATION,I_016_01_NATL_OBS_RATE,77.10,-,10/01/2024,03/31/2025,-
6,NATION,I_017_01_PPR_PD_NATL_OBS_RATE,9.21,-,10/01/2022,09/30/2024,-
7,NATION,I_017_01_PPR_PD_N_BETTER_NATL,19,-,10/01/2022,09/30/2024,-
8,NATION,I_017_01_PPR_PD_N_NO_DIFF_NATL,"1,101",-,10/01/2022,09/30/2024,-
9,NATION,I_017_01_PPR_PD_N_TOO_SMALL,19,-,10/01/2022,09/30/2024,-
10,NATION,I_017_01_PPR_PD_N_WORSE_NATL,55,-,10/01/2022,09/30/2024,-

Csv_data1 presents the follwoing:


1. **CMS Certificate Number** Identifies the reporting facility or reporting level. The value `NATION` indicates that the row contains a national result rather than the result of an individual healthcare facility
2. **Measure Code** the unique code used to identify the healthcare quality or infection measure being reported.
3. **Score:** The national result for the measure. Depending on the measure code, the score may represent a standardized infection ratio, an observed rate, or the number of facilities in a performance category.
4. **Footnote:** Provides additional information or qualifications about the reported result. A dash (`-`) indicates that no footnote was provided.
5. **Start Date:** The beginning of the period during which data for the measure were collected.
6. **End Date:** The end of the period during which data for the measure were collected.
7. **Measure Date Range:** Provides a combined or additional description of the measurement period when available. A dash (`-`) indicates that no additional date range was reported.

**what the code do?**
we need this code so that pandas can read the csv dataset.

In [ ]:
import pandas as pd
df2 = '/content/data /data2.csv'

read_csv2 = pd.read_csv(df2)
read_csv2.head(11)

,GHO (CODE),GHO (DISPLAY),GHO (URL),YEAR (DISPLAY),STARTYEAR,ENDYEAR,REGION (CODE),REGION (DISPLAY),COUNTRY (CODE),COUNTRY (DISPLAY),DIMENSION (TYPE),DIMENSION (CODE),DIMENSION (NAME),Numeric,Value,Low,High
0,WHS6_102,Hospital beds (per 10 000 population),https://www.who.int/data/gho/data/indicators/i...,2010,2010,2010,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,20.00000,20.00,NaN,NaN
1,DEVICES05,Total density per 100 000 population: Speciali...,https://www.who.int/data/gho/data/indicators/i...,2010,2010,2010,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,0.04000,0.04,NaN,NaN
2,DEVICES01,Total density per 100 000 population: Health p...,https://www.who.int/data/gho/data/indicators/i...,2013,2013,2013,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,1.17618,1.18,NaN,NaN
3,DEVICES05,Total density per 100 000 population: Speciali...,https://www.who.int/data/gho/data/indicators/i...,2013,2013,2013,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,0.03439,0.03,NaN,NaN
4,DEVICES04,Total density per 100 000 population: Provinci...,https://www.who.int/data/gho/data/indicators/i...,2010,2010,2010,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,0.14000,0.14,NaN,NaN
5,DEVICES02,Total density per 100 000 population: Health c...,https://www.who.int/data/gho/data/indicators/i...,2010,2010,2010,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,9.25000,9.25,NaN,NaN
6,DEVICES02,Total density per 100 000 population: Health c...,https://www.who.int/data/gho/data/indicators/i...,2013,2013,2013,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,8.32953,8.33,NaN,NaN
7,DEVICES00,Total density per 100 000 population: Hospitals,https://www.who.int/data/gho/data/indicators/i...,2013,2013,2013,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,0.45396,0.45,NaN,NaN
8,DEVICES03,Total density per 100 000 population: District...,https://www.who.int/data/gho/data/indicators/i...,2013,2013,2013,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,0.29576,0.30,NaN,NaN
9,DEVICES04,Total density per 100 000 population: Provinci...,https://www.who.int/data/gho/data/indicators/i...,2013,2013,2013,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,0.12381,0.12,NaN,NaN
10,WHS6_102,Hospital beds (per 10 000 population),https://www.who.int/data/gho/data/indicators/i...,2008,2008,2008,AFR,Africa,ZMB,Zambia,NaN,NaN,NaN,19.00000,19.00,NaN,NaN

WHO Global Health Observatory Dataset Features

- **GHO (CODE):** The identification code assigned by the World Health Organization to each health indicator.
- **GHO (DISPLAY):** The name or description of the health indicator being measured.
- **GHO (URL):** A link to the WHO webpage containing information about the indicator.
- **YEAR (DISPLAY):** The year associated with the reported result.
- **STARTYEAR:** The first year of the measurement period.
- **ENDYEAR:** The last year of the measurement period.
- **REGION (CODE):** The abbreviated WHO code for the geographic region. For example, `AFR` represents Africa.
- **REGION (DISPLAY):** The complete name of the WHO geographic region.
- **COUNTRY (CODE):** The three-letter code used to identify the country. For example, `ZMB` represents Zambia.
- **COUNTRY (DISPLAY):** The complete name of the country.
- **DIMENSION (TYPE):** The type of additional category used to separate the data, when applicable.
- **DIMENSION (CODE):** The code assigned to an additional data category, when applicable.
- **DIMENSION (NAME):** The name of the additional data category, when applicable.
- **Numeric:** The complete numerical result for the health indicator.
- **Value:** The displayed or rounded version of the numerical result.
- **Low:** The lower limit of the estimated result, when available.
- **High:** The upper limit of the estimated result, when available.

**Note:** `NaN` means that a value is missing or was not provided. The numbers shown on the far left are row indexes and are not dataset features.

In [ ]:
import pandas as pd
df3 ='/content/Financial Sample.xlsx'

read_xlsx1 = pd.read_excel(df3)
read_xlsx1.head(11)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,NaN,888.0,3,15,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014
5,Government,Germany,Carretera,NaN,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
6,Midmarket,Germany,Montana,NaN,921.0,5,15,13815.0,0.0,13815.0,9210.0,4605.0,2014-03-01,3,March,2014
7,Channel Partners,Canada,Montana,NaN,2518.0,5,12,30216.0,0.0,30216.0,7554.0,22662.0,2014-06-01,6,June,2014
8,Government,France,Montana,NaN,1899.0,5,20,37980.0,0.0,37980.0,18990.0,18990.0,2014-06-01,6,June,2014
9,Channel Partners,Germany,Montana,NaN,1545.0,5,12,18540.0,0.0,18540.0,4635.0,13905.0,2014-06-01,6,June,2014
10,Midmarket,Mexico,Montana,NaN,2470.0,5,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014

Customer Purchase Dataset Features

- **CUST_NAME:** Customer’s name.
- **Gender_Code:** Customer’s gender or title.
- **ADDRESS1 and ADDRESS2:** Customer’s street address.
- **CITY, STATE, and COUNTRY_CODE:** Customer’s geographic location.
- **POSTAL_CODE and POSTAL_CODE_PLUS4:** Customer’s postal information.
- **EMAIL_ADDRESS:** Customer’s email address.
- **Product category columns:** Indicate whether the customer purchased from each category; `1` means yes and `0` means no.
- **NaN:** Indicates missing information.

In [37]:
import pandas as pd
df4 = '/content/data /supplier-diversity-regional-plan-2023_10202025.xlsx'

read_xlsx2 = pd.read_excel(df4)
read_xlsx2.head(11)

,Hospital_Region_ID,Region_Name,Associated_Hospitals,System_Reporting_Organization,System_Description,System_Report_Start_Date,System_Report_End_Date,System_Require_Certification,System_Self_Certification,System_Tier_I_African_American,...,System_Tier_II_Disabled_Veteran,System_Total_Disabled_Veteran,System_Tier_I_Less_Duplicated_Amount,System_Tier_II_Less_Duplicated_Amount,System_Total_Less_Duplicated_Amount,System_Combined_Tier_I_Total,System_Combined_Tier_II_Total,System_Combined_Total,System_Total_Hospital_Procurement,System_Other_Relevant_Info
0,4,Palomar Health,"106370977,106374382",Palomar Health,This is spend associated with Palomar Health (...,2023-01-01 08:00:00,2023-12-31 08:00:00,No,No,42684.0,...,NaN,614619.0,1131564.0,NaN,1131564.0,3160938.0,NaN,3160938,60169704,NaN
1,11,John Muir Health,"106070988,106071018,106074039",John Muir Health,John Muir Health is a not-for-profit integrate...,2023-01-01 08:00:00,2023-12-31 08:00:00,Yes,No,8814.0,...,65146.0,134200.0,409008.0,NaN,409008.0,821992.0,936812.0,1758804,758411819,Total procurement (including diverse and non-d...
2,1,Adventist Health System/West,"106100793,106100797,106150706,106150788,106154...",Adventist Health System/West,Includes spend for all Adventist Health System...,2023-01-01 08:00:00,2023-12-31 08:00:00,Yes,Yes,3100434.0,...,NaN,1935304.0,5232288.0,NaN,5232288.0,33305552.0,NaN,33305552,2086768270,The procurement dollars listed are representat...
3,8,Sharp HealthCare System Report,"106370689,106370694,106370695,106370714,106370...",Sharp HealthCare,This is a System wide report for Sharp HealthC...,2023-01-01 08:00:00,2023-12-31 08:00:00,Yes,No,3024265.0,...,1038.0,356855.0,0.0,0.0,0.0,63634282.0,873340.0,64507622,2265159845,Sharp HealthCare's mission is to promote and p...
4,3,Keck Medicine of USC,"106190529,106190818,106191216,106194219",Keck Medicine of USC,Keck Medicine of USC is the University of Sout...,2023-01-01 08:00:00,2023-12-31 08:00:00,Yes,Yes,1623162.0,...,NaN,1927140.0,11275569.0,NaN,11275569.0,31500037.0,NaN,31500037,1062802976,Keck Medicine of USC is proud to have done bus...
5,12,MARIAN REGIONAL MEDICAL CENTER - GROUP,"106400466,106420493",CommonSpirit Health,This system report includes data for the follo...,2023-01-01 08:00:00,2023-12-31 08:00:00,Yes,Yes,NaN,...,NaN,510.0,NaN,NaN,NaN,582575.0,NaN,582575,181354589,Aligning with the Healthcare Anchor Network’s ...
6,13,MERCY HOSPITAL - BAKERSFIELD - GROUP,"106150761,106154108",CommonSpirit Health,This system report includes data for the follo...,2023-01-01 08:00:00,2023-12-31 08:00:00,Yes,Yes,NaN,...,NaN,NaN,NaN,NaN,NaN,1700244.0,NaN,1700244,101148452,“System report submitted for Mercy Hospital Ba...
7,18,Community Memorial Health System,"106560473,106560501",Community Memorial Health System,System-level report for HCAI IDs \n\n106560501...,2023-01-01 08:00:00,2023-12-31 08:00:00,Yes,No,0.0,...,0.0,0.0,37846.0,NaN,37846.0,354932.0,0.0,354932,78530772,Outreach Programs\nCommunity Memorial Health S...
8,2,Alameda Health System,"106010735,106010811,106010846,106013619",Alameda Health System,Alameda Health System (AHS) is an integrated p...,2023-01-01 08:00:00,2023-12-31 08:00:00,No,No,701550.0,...,0.0,0.0,16998264.0,NaN,16998264.0,17052439.0,0.0,17052439,317422959,AHS financial reporting systems are currently ...
9,7,Scripps,"106370744,106370771,106371256,106371394",Scripps Health,"Scripps Memorial Encinitas, Scripps Memorial L...",2023-01-01 08:00:00,2023-12-31 08:00:00,Yes,No,1340442.0,...,18234.0,1284317.0,55708.0,40843.0,96551.0,57126285.0,664302.0,57790587,702399255,NaN
10,6,Providence - All CA,"106121051,106121080,106190385,106190470,106190...",Providence,Providence,2023-01-01 08:00:00,2023-12-31 08:00:00,No,No,NaN,...,300785.0,300785.0,NaN,NaN,NaN,NaN,51571866.0,51571866,1847787628,The Tier II Data that is reported includes the...

Hospital Procurement Dataset Features

- **Hospital_Region_ID:** Unique number assigned to the hospital region.
- **Region_Name:** Name of the hospital or healthcare region.
- **Associated_Hospitals:** Identification numbers of hospitals included in the report.
- **System_Reporting_Organization:** Organization that submitted the report.
- **System_Description:** Description of the healthcare system and reported data.
- **System_Report_Start_Date:** Beginning of the reporting period.
- **System_Report_End_Date:** End of the reporting period.
- **System_Require_Certification:** Indicates whether certification is required.
- **System_Self_Certification:** Indicates whether the organization certified its own report.
- **System_Tier_I_African_American:** Tier I spending with African American-owned suppliers.
- **System_Tier_II_Disabled_Veteran:** Tier II spending with disabled veteran-owned suppliers.
- **System_Total_Disabled_Veteran:** Total spending with disabled veteran-owned suppliers.
- **System_Tier_I_Less_Duplicated_Amount:** Tier I spending after removing duplicated amounts.
- **System_Tier_II_Less_Duplicated_Amount:** Tier II spending after removing duplicated amounts.
- **System_Total_Less_Duplicated_Amount:** Total spending after removing duplicated amounts.
- **System_Combined_Tier_I_Total:** Total Tier I procurement spending.
- **System_Combined_Tier_II_Total:** Total Tier II procurement spending.
- **System_Combined_Total:** Combined Tier I and Tier II spending.
- **System_Total_Hospital_Procurement:** Total procurement spending reported by the hospital system.
- **System_Other_Relevant_Info:** Additional information supplied by the organization.
- **NaN:** Indicates missing or unreported information.

In [39]:
import pandas as pd
df5 = '/content/data /supplier-diversity-plan-2022-extract.xlsx'

read_xslx3 = pd.read_excel(df5)
read_xslx3.head(11)

,Hospital_Name,Hospital_Address,HCAI_ID,License_Number,Licensee,Type_Control,County,MSSA,HSA,HFPA,...,Combined_Total,Total_Hospital_Procurement,Contact_Name,Contact_Email,Contact_Phone_Number,Website_Link,Third_Party,Third_Party_Name,Third_Party_Website,Other_Relevant_Info
0,RADY CHILDREN'S HOSPITAL - SAN DIEGO,"3020 CHILDREN'S WAY, SAN DIEGO, CA 92123",106370673,080000028,RADY CHILDREN'S HOSPITAL - SAN DIEGO,Non-profit Corporation (incl. Church-related),San Diego,Urban,14 - San Diego/Imperial,1416.0,...,12344171.0,287728694,MARGARET MOORE,NaN,NaN,NaN,No,NaN,NaN,NaN
1,UCSF BENIOFF CHILDREN'S HOSPITAL OAKLAND,"747 52ND STREET, OAKLAND, CA 94609",106010776,140000015,CHILDREN'S HOSPITAL & RESEARCH CENTER OAKLAND,Non-profit Corporation (incl. Church-related),Alameda,Urban,05 - East Bay,417.0,...,5509158.0,200000000,Eamon,NaN,NaN,NaN,Yes,Vizient,www.Vizientinc.com,NaN
2,CITY OF HOPE HELFORD CLINICAL RESEARCH HOSPITAL,"1500 DUARTE ROAD, DUARTE, CA 91010",106190176,930000033,CITY OF HOPE NATIONAL MEDICAL CENTER,Non-profit Corporation (incl. Church-related),Los Angeles,Urban,11 - Los Angeles,913.0,...,13719388.0,1155288548,Flora Mayer,NaN,NaN,www.cityofhope.org,Yes,Vizient,www.vizient.com,NaN
3,CHILDREN'S HOSPITAL OF LOS ANGELES,"4650 W. SUNSET BOULEVARD, LOS ANGELES, CA 90027",106190170,930000032,CHILDREN'S HOSPITAL OF LOS ANGELES,Non-profit Corporation (incl. Church-related),Los Angeles,Urban,11 - Los Angeles,925.0,...,20558225.0,615739382,Audrey Chang,NaN,NaN,https://www.chla.org/supplier-diversity-progra...,Yes,Vizient,https://www.vizientinc.com/,NaN
4,HOLLYWOOD PRESBYTERIAN MEDICAL CENTER,"1300 NORTH VERMONT AVENUE, LOS ANGELES, CA 90027",106190382,930000067,"CHA HOLLYWOOD MEDICAL CENTER, L.P.",Investor - Partnership,Los Angeles,Urban,11 - Los Angeles,925.0,...,1692847.0,234344124,Dagmar Wilson,NaN,NaN,NaN,Yes,Vizient,https://www.vizientinc.com/,NaN
5,PORTERVILLE DEVELOPMENTAL CENTER,"26501 AVENUE 140, PORTERVILLE, CA 93257",106541123,170000837,STATE OF CALIF. DEPT. OF DEVELOPMENTAL SERVICES,State,Tulare,Rural,09 - Central,613.0,...,10641249.0,23079149,Maria Lopez,NaN,NaN,NaN,No,NaN,NaN,NaN
6,SHRINERS HOSPITALS FOR CHILDREN NORTHERN CALIF.,"2425 STOCKTON BLVD, SACRAMENTO, CA 95817",106344114,030000620,SHRINERS HOSPITALS FOR CHILDREN,Non-profit Corporation (incl. Church-related),Sacramento,Urban,02 - Golden Empire,311.0,...,212868.0,10652095,James Lucas,NaN,NaN,NaN,No,NaN,NaN,NaN
7,PALOMAR MEDICAL CENTER POWAY,"15615 POMERADO ROAD, POWAY, CA 92064",106370977,080000127,PALOMAR HEALTH,District,San Diego,Urban,14 - San Diego/Imperial,1412.0,...,951699.0,48383875,Kyle Menig,NaN,NaN,NaN,Yes,HealthTrust,https://healthtrustpg.com,This is for Palomar Medical Center Poway in Po...
8,BARLOW RESPIRATORY HOSPITAL,"2000 STADIUM WAY, LOS ANGELES, CA 90026",106190052,930000011,THE BARLOW HOSPITAL,Non-profit Corporation (incl. Church-related),Los Angeles,Urban,11 - Los Angeles,925.0,...,121777.0,5488121,Donna Belich-Kraus,NaN,NaN,NaN,Yes,CHC,www.communityhospitalcorporation,NaN
9,COMMUNITY HOSPITAL OF THE MONTEREY PENINSULA,"23625 W. R. HOLMAN HIGHWAY, MONTEREY, CA 93940",106270744,070000026,COMMUNITY HOSPITAL OF THE MONTEREY PENINSULA,Non-profit Corporation (incl. Church-related),Monterey,Urban,08 - Mid-Coast,707.0,...,602411.0,72616777,Douglas Clark,NaN,NaN,NaN,Yes,Vizient,https://www.vizientinc.com/member-login,NaN
10,STANFORD HEALTH CARE TRI-VALLEY,"5555 WEST LAS POSITAS BLVD., PLEASANTON, CA 94588",106014050,140000114,STANFORD HEALTH CARE TRI-VALLEY,Non-profit Corporation (incl. Church-related),Alameda,Urban,05 - East Bay,419.0,...,5471146.0,119162739,Leslie Fleming,NaN,NaN,https://stanfordhealthcare.org/about-us/suppli...,Yes,Vizient,www.vizientinc.com,NaN

Hospital Procurement Dataset Features

- **Hospital_Name:** Name of the hospital.
- **Hospital_Address:** Hospital’s business address.
- **HCAI_ID:** Identification number assigned to the hospital by HCAI.
- **License_Number:** California-issued hospital license number.
- **Licensee:** Organization that holds the hospital’s license.
- **Type_Control:** Hospital’s ownership or control type.
- **County:** County where the hospital is located.
- **MSSA:** Hospital’s Medical Service Study Area.
- **HSA:** Hospital’s Health Service Area.
- **HFPA:** Hospital’s Health Facility Planning Area.
- **Combined_Total:** Total spending with diverse suppliers.
- **Total_Hospital_Procurement:** Hospital’s total procurement spending.
- **Contact_Name:** Name of the hospital’s supplier contact.
- **Contact_Email:** Email address of the supplier contact.
- **Contact_Phone_Number:** Phone number of the supplier contact.
- **Website_Link:** Hospital’s supplier or procurement website.
- **Third_Party:** Indicates whether a third-party procurement company is used.
- **Third_Party_Name:** Name of the third-party procurement company.
- **Third_Party_Website:** Website of the third-party company.
- **Other_Relevant_Info:** Additional information provided by the hospital.

In [41]:
import json
df6 ='/content/budgets.json'

read_json = pd.read_json(df6)
read_json.head(11)

    budgetYear  forecastYear  value
0         1980          1980 -0.103
1         1980          1981 -0.037
2         1980          1982  0.010
3         1980          1983  0.051
4         1981          1980 -0.192
5         1981          1981 -0.129
6         1981          1982 -0.060
7         1981          1983 -0.017
8         1981          1984  0.063
9         1982          1981 -0.185
10        1982          1982 -0.215

Federal Budget Dataset Features

- **budgetYear:** The year when the budget projection was created.
- **forecastYear:** The year covered by the projection.
- **value:** The projected or actual federal budget result in trillions of dollars. Negative values represent deficits, while positive values represent surpluses.

In [42]:
import json
df7 = '/content/cars.json'

read_json = pd.read_json(df7)
read_json.head(11)

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA
5,ford galaxie 500,15.0,8,429.0,198.0,4341,10.0,1970-01-01,USA
6,chevrolet impala,14.0,8,454.0,220.0,4354,9.0,1970-01-01,USA
7,plymouth fury iii,14.0,8,440.0,215.0,4312,8.5,1970-01-01,USA
8,pontiac catalina,14.0,8,455.0,225.0,4425,10.0,1970-01-01,USA
9,amc ambassador dpl,15.0,8,390.0,190.0,3850,8.5,1970-01-01,USA
10,citroen ds-21 pallas,NaN,4,133.0,115.0,3090,17.5,1970-01-01,Europe

Automobile Dataset Features

- **Name:** Make and model of the vehicle.
- **Miles_per_Gallon:** Vehicle’s estimated fuel efficiency in miles per gallon.
- **Cylinders:** Number of engine cylinders.
- **Displacement:** Engine displacement measured in cubic inches.
- **Horsepower:** Engine power measured in horsepower.
- **Weight_in_lbs:** Vehicle weight measured in pounds.
- **Acceleration:** Time required to accelerate from 0 to 60 miles per hour, measured in seconds.
- **Year:** Vehicle’s model year.
- **Origin:** Region where the vehicle was manufactured.

In [46]:
import json
df8 = '/content/crimea.json'

read_json = pd.read_json(df8)
read_json.head(11)

         date  wounds  other  disease  army_size
0  1854-04-01       0      5        1       8571
1  1854-05-01       0      9       12      23333
2  1854-06-01       0      6       11      28333
3  1854-07-01       0     23      359      28722
4  1854-08-01       1     30      828      30246
5  1854-09-01      81     70      788      30290
6  1854-10-01     132    128      503      30643
7  1854-11-01     287    106      844      29736
8  1854-12-01     114    131     1725      32779
9  1855-01-01      83    324     2761      32393
10 1855-02-01      42    361     2120      30919

Crimean War Mortality Dataset Features

- **date:** Month and year when the information was recorded.
- **wounds:** Number of deaths caused by wounds and injuries.
- **other:** Number of deaths caused by other conditions.
- **disease:** Number of deaths caused by preventable infectious diseases.
- **army_size:** Estimated average number of soldiers in the army during that month.